name: Cypress Tests Run on Pipeline

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run
          start: npm start
          browser: chrome

      - name: Run Cypress API tests
        run: npx cypress run --spec "cypress/e2e/usuarios.cy.js"
